### ISSUE TITLE
Any tips for getting started?

### ISSUE THREAD

**Issue by pomalley** [jdleslie/sage2-boiler#1]
Thanks for putting this together!

Do you have any tips for getting the connection set up in the first place? I have a Burnham Alpine boiler and I think I've got the RS-485 connection wired correctly, but I'm not getting any response from the boiler. Is there a setting you had to enable (e.g. on the LCD on the unit)? Any other tricky things to be aware of? I'm not at all familiar with RS-485 or modbus so I could be missing something obvious.

(I'm just trying to get this working over serial right now.)

**Comment by jdleslie** [comment]
I don't recall anything to enable in the controller-- default method to connect in this script is ModBus/TCP (not RTU). If you are using a USB-RS485 adapter then check that the script is using it

**Comment by pomalley** [comment]
Yes, I have a USB-RS485 adapter--[this one](https://www.waveshare.com/usb-to-rs485.htm). I think I've got it wired correctly--pin 1 (white/orange) to data +, pin 2 (orange) to data -, pin 3 (white/green) to ground, and 38400 baud as stated in the sage2 doc. I'm running the script like so:

```python
if __name__ == '__main__':
    import serial
    import sys

    s = serial.Serial('/dev/ttyUSB0', baudrate=38400)

    # Modbus/TCP bridge can be specified as an argument
    host = len(sys.argv) == 2 and sys.argv[1] or 'localhost'

    boiler = Sage2Boiler(slave=1, host=host, port=502, serial=s)

    print(boiler.tabulate(summary=True))
```

I see the TX light blink but nothing on RX so it seems nothing is coming back. (The error is `Response length is invalid 0`--makes sense, I guess.) I've also tried just using `modbus_tk` directly to send a `READ_HOLDING_REGISTERS` but that gives the same error. That was leading me to wonder if there is something I need to do on the controller side, but I guess not.

**Comment by jdleslie** [comment]
Your wiring and example look fine. I have been using a ModBus/RTU-TCP bridge for a few years with success, but can find my cable and try out RTU mode again.

**Comment by jdleslie** [comment]
Found my USB RS485 cable and was able to reproduce your issue. Fiddling with the timeout seems to address things, so I picked a value that works reliably for me at 38400 baud. Try pulling the latest commit and re-testing.

**Comment by pomalley** [comment]
Thanks so much for helping out. Sadly that did not make a difference on my end. I'm going to assume that something about my wiring or configuration is incorrect.

According to [this doc](https://mini-monitor-documentation.readthedocs.io/en/latest/available-sensor-readers.html#sage-2-1-boiler-control-used-in-burnham-alpine-boilers) on the [mini-monitor](https://git.ahfc.us/energy/mini-monitor) project (which I only found by scrolling down the Google results, heh), the boiler needs to be set to a slave address e.g. of 1. Did you do something like that?

**Comment by jdleslie** [comment]
> Did you do something like that?

I don’t recall, but it is possible. The mini-monitor docs are pretty clear that it is required and non-default. Give it a try and share your results?

> The Factory default for this setting is “None”, so it must be changed in order for the monitoring system to work.

**Comment by pomalley** [comment]
Ha! It turns out my wiring was wrong; according to [this part](https://mini-monitor-documentation.readthedocs.io/en/latest/hardware.html#parts-cv1-and-j1-burnham-alpine-boiler-interface) of the mini-monitor doc:

> There are two connections required from the EKM RS485 converter to the RJ45 jack: the + connection on RS485 converter goes to **pin 8** of the RJ45, and - connection goes to **pin 7**.

So I rewired to brown, brown-white, and green and it works! Sorry for the hassle.

I'd be happy to contribute whatever I end up doing with this, if you add an OS license to the repo (requirement of my employer).

**Comment by jdleslie** [comment]
Will close this issue. I've added a license file-- PRs welcome!
